sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - sudo apt-get install -y openssl
  - pip install "zeroc-ice>3.6.4,<3.7" future
  - python -c "import Ice; print Ice.stringVersion()"

script:
  - python setup.py sdist
  - pip install dist/omero-py*gz
  - python -c "import omero_version; print omero_version.omero_version"
  - omero version
  - docker build -t test .

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
