sudo: false

language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.6"
      env: TOX=no

install:
  - |
    if [ "$TOX" = "no" ]; then
      pip install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.1.0/zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
      pip install restructuredtext-lint
    else
      pip install tox-travis
    fi

script:
  - |
    if [ "$TOX" = "no" ]; then
      rst-lint README.rst
      python setup.py sdist
      pip install dist/omero-py*gz
      omero version
    else
      tox
    fi

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
    condition: "$TOX = no"
